# Generated by Django 4.1.2 on 2024-07-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='urlImg',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
